In [2]:
import pandas as pd
pd.set_option('display.max_colwidth', 100)

In [3]:
df = pd.read_csv('sample.csv')
df

text  \
0                                        Meditation and yoga can improve mental health   
1                     Fruits, whole grains and vegetables helps control blood pressure   
2                                    These are the latest fashion trends for this week   
3                                    Vibrant color jeans for male are becoming a trend   
4                                                   The concert starts at 7 PM tonight   
5                      Navaratri dandiya program at Expo center in Mumbai this october   
6                                    Exciting vacation destinations for your next trip   
7  Maldives and Srilanka are gaining popularity in terms of low budget vacation places   

  category  
0   Health  
1   Health  
2  Fashion  
3  Fashion  
4    Event  
5    Event  
6   Travel  
7   Travel

In [4]:
from sentence_transformers import SentenceTransformer
encoder = SentenceTransformer('all-mpnet-base-v2')
vectors = encoder.encode(df.text)
vectors.shape

.gitattributes: 100%|█████████████████████████████████████████████████████████████| 1.18k/1.18k [00:00<?, ?B/s]
1_Pooling/config.json: 100%|███████████████████████████████████████████████████| 190/190 [00:00<00:00, 190kB/s]
README.md: 100%|██████████████████████████████████████████████████████████| 10.6k/10.6k [00:00<00:00, 5.27MB/s]
config_sentence_transformers.json: 100%|███████████████████████████████████████| 116/116 [00:00<00:00, 116kB/s]
data_config.json: 100%|███████████████████████████████████████████████████| 39.3k/39.3k [00:00<00:00, 13.1MB/s]
pytorch_model.bin: 100%|████████████████████████████████████████████████████| 438M/438M [01:20<00:00, 5.43MB/s]
sentence_bert_config.json: 100%|████████████████████████████████████████████████████| 53.0/53.0 [00:00<?, ?B/s]
special_tokens_map.json: 100%|████████████████████████████████████████████████████████| 239/239 [00:00<?, ?B/s]
tokenizer.json: 100%|███████████████████████████████████████████████████████| 466k/466k [00:00<00:00, 1.

(8, 768)

In [5]:
dim = vectors.shape[1]

In [6]:
import faiss

index = faiss.IndexFlatL2(dim)
index.add(vectors)

In [7]:
search_query = 'I wanna buy a polo t-shirt'
vec = encoder.encode(search_query)

In [9]:
vec.shape

(768,)

In [10]:
import numpy as np
svec = np.array(vec).reshape(1, -1)
svec.shape

(1, 768)

In [11]:
svec

array([[-3.13444645e-03,  5.63511401e-02, -4.43540746e-03,
        -1.33915048e-03,  1.29751815e-02, -1.73978992e-02,
        -1.42708719e-02,  3.21515352e-02, -2.82508768e-02,
         3.26816402e-02, -2.54765362e-03,  3.25989095e-03,
         1.40942391e-02,  7.48299882e-02,  1.76416319e-02,
        -1.65598784e-02,  7.14487489e-03, -3.09292544e-02,
         8.07336345e-02, -1.09097501e-02,  3.32058370e-02,
         9.47576202e-03, -2.07567830e-02,  3.24215777e-02,
         8.59598804e-04, -6.45528138e-02,  3.00554298e-02,
        -1.18681462e-02, -3.12434174e-02,  1.25445416e-02,
         3.05903479e-02,  1.83798186e-02, -2.75787432e-02,
        -4.12376039e-02,  1.34103777e-06, -9.46295168e-03,
        -1.75572410e-02, -6.00932240e-02, -1.23745315e-02,
        -1.19519094e-02, -2.60808822e-02,  4.74103875e-02,
        -2.69156359e-02, -4.04938404e-03, -1.50469337e-02,
        -3.27985659e-02,  4.69235778e-02,  1.28563598e-01,
        -8.68839025e-02,  1.39054572e-02, -1.45034632e-0

In [12]:
index.search(svec, k = 2)

(array([[1.3409157, 1.3668225]], dtype=float32), array([[3, 2]], dtype=int64))

In [13]:
distance, I = index.search(svec, k = 2)

In [14]:
I

array([[3, 2]], dtype=int64)

In [16]:
df.loc[[3,2]]

text category
3  Vibrant color jeans for male are becoming a trend  Fashion
2  These are the latest fashion trends for this week  Fashion